In [17]:
from tensorflow.keras.preprocessing.text import one_hot
import warnings
warnings.filterwarnings("ignore")

In [18]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [29]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
## Define the vocabulary size
voc_size = 10000

In [21]:
### One Hot Representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3983, 2379, 491, 3086],
 [3983, 2379, 491, 6367],
 [3983, 17, 491, 1372],
 [9782, 5015, 6447, 7478, 1190],
 [9782, 5015, 6447, 7478, 5715],
 [7032, 3983, 6180, 491, 2625],
 [736, 5585, 1818, 7478]]

In [ ]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [25]:
# keep length to max in corpus
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 3983 2379  491 3086]
 [   0    0    0    0 3983 2379  491 6367]
 [   0    0    0    0 3983   17  491 1372]
 [   0    0    0 9782 5015 6447 7478 1190]
 [   0    0    0 9782 5015 6447 7478 5715]
 [   0    0    0 7032 3983 6180  491 2625]
 [   0    0    0    0  736 5585 1818 7478]]


In [26]:
## feature representation
dim = 10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\chaub\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.predict(embedded_docs).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


(7, 8, 10)

In [37]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[[-4.45462465e-02,  3.85779627e-02, -4.96766083e-02,
          4.47340123e-02,  4.05599587e-02,  3.31905000e-02,
          1.94377564e-02,  3.56796421e-02,  2.20981985e-03,
         -5.68566471e-03],
        [-4.45462465e-02,  3.85779627e-02, -4.96766083e-02,
          4.47340123e-02,  4.05599587e-02,  3.31905000e-02,
          1.94377564e-02,  3.56796421e-02,  2.20981985e-03,
         -5.68566471e-03],
        [-4.45462465e-02,  3.85779627e-02, -4.96766083e-02,
          4.47340123e-02,  4.05599587e-02,  3.31905000e-02,
          1.94377564e-02,  3.56796421e-02,  2.20981985e-03,
         -5.68566471e-03],
        [-4.45462465e-02,  3.85779627e-02, -4.96766083e-02,
          4.47340123e-02,  4.05599587e-02,  3.31905000e-02,
          1.94377564e-02,  3.56796421e-02,  2.20981985e-03,
         -5.68566471e-03],
        [ 5.30257821e-05, -4.82140183e-02, -2.82421950e-02,
          3.41261290e-02, -4.00286317e-02,  4.72040214e-02,
          2.81096622e-03,  5.06711006e-03,  1.070866